name = "Romangho Valley"
author = "Rw"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ce83ca9a009542b907beb2aa4adb9dd8c398a88d69e717ad1a52be805d3b42c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
