name = "Romangho Valley"
author = "Rw"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb980eb97ca68d06e9e2205e469b69795d64aa45cc2fddd668bcc95c51a18967"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
