#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 23 20:15:26 KST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.6.1 + Clrwl_1.0.4.zip
enableShaders=false
